### ISSUE TITLE
Research: Use image upload to DB

### ISSUE THREAD

**Issue by Lonrot** [Spring-Samurais/toy-swap-backend#6]
How to use of PostgreSQL for images or MongoDB (any non-relational DB) and link it to Post

**Comment by Lonrot** [comment]
javax.imageio can serialize and deserialize from byte to PNG 
[Overview](https://www.javatpoint.com/java-imageio-class)

@bm298 @Ainkharan  what do you think?

**Comment by bm298** [comment]
https://www.youtube.com/watch?v=XUL60-Ke-L8&t=0s

**Comment by bm298** [comment]
public class ImageData {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private String type;

    @Lob
    private byte[] imageData;

    // all the getters 
}

**Comment by bm298** [comment]
public String uploadImage(MultipartFile file) throws IOException {
        String fileName = file.getOriginalFilename();
        ImageData imageData = ImageData.builder()
                .name(fileName)
                .type(file.getContentType())
                .imageData(compressBytes(file.getBytes()))
                .build();

        repository.save(imageData);
        return "File uploaded successfully: " + fileName;
    }
